logging:
  level:
    cz.rockawayx.stakingrewardsapi.client: DEBUG

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:

app:
  rockawayx-validators-cosmos-url: https://validators.cosmos.directory/RockawayXInfra/staking-rewards
  rockawayx-assets-directory: ./rockawayx-assets
spring:
  cloud:
    openfeign:
      autoconfiguration:
        jackson:
          enabled:
